version: "3.9"

services:

  demo:
    image: docker.unholster.com/trialstreamer-demo
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - 8080:80