version: "3.9"

services:

  trialstreamer-demo:
    image: docker.unholster.com/trialstreamer-demo
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/app/
    restart: always
    ports:
      - 8080:8080